version: 2

project_name: crush

builds:
  - env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=greenteagc
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags:
      - -s -w -X github.com/charmbracelet/crush/internal/version.Version={{.Version}}

archives:
  - name_template: "crush_{{ .Version }}_{{ title .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README*
      - LICENSE*

checksum:
  name_template: checksums.txt

changelog:
  use: git
  sort: asc

release:
  prerelease: auto
